const palette = {
  mint: "#34C78B",
  mintLight: "#E8F8F2",
  mintDark: "#1E9966",
  coral: "#FF6B6B",
  coralLight: "#FFF0F0",
  coralDark: "#E04444",
  blue: "#007AFF",
  blueLight: "#E8F2FF",
  amber: "#FF9F0A",
  amberLight: "#FFF5E6",
  purple: "#AF52DE",
  purpleLight: "#F5EAFF",

  white: "#FFFFFF",
  gray50: "#F9FAFB",
  gray100: "#F2F3F5",
  gray200: "#E5E7EB",
  gray300: "#D1D5DB",
  gray400: "#9CA3AF",
  gray500: "#6B7280",
  gray600: "#4B5563",
  gray700: "#374151",
  gray800: "#1F2937",
  gray900: "#111827",
  black: "#000000",

  darkBg: "#0A0A0A",
  darkSurface: "#141414",
  darkCard: "#1C1C1E",
  darkBorder: "#2C2C2E",
  darkText: "#FFFFFF",
  darkTextSecondary: "rgba(255,255,255,0.6)",
  darkTextTertiary: "rgba(255,255,255,0.35)",
};

export default {
  light: {
    text: palette.gray900,
    textSecondary: palette.gray500,
    textTertiary: palette.gray400,
    background: palette.gray50,
    surface: palette.white,
    card: palette.white,
    border: palette.gray200,
    borderLight: palette.gray100,
    tint: palette.mint,
    tintDark: palette.mintDark,
    tintLight: palette.mintLight,
    accent: palette.coral,
    accentLight: palette.coralLight,
    blue: palette.blue,
    blueLight: palette.blueLight,
    amber: palette.amber,
    amberLight: palette.amberLight,
    purple: palette.purple,
    purpleLight: palette.purpleLight,
    tabIconDefault: palette.gray400,
    tabIconSelected: palette.mint,
    danger: palette.coral,
    warning: palette.amber,
    success: palette.mint,
  },
  dark: {
    text: palette.darkText,
    textSecondary: palette.darkTextSecondary,
    textTertiary: palette.darkTextTertiary,
    background: palette.darkBg,
    surface: palette.darkSurface,
    card: palette.darkCard,
    border: palette.darkBorder,
    borderLight: "rgba(255,255,255,0.06)",
    tint: palette.mint,
    tintDark: palette.mintDark,
    tintLight: "rgba(52,199,139,0.15)",
    accent: palette.coral,
    accentLight: "rgba(255,107,107,0.15)",
    blue: palette.blue,
    blueLight: "rgba(0,122,255,0.15)",
    amber: palette.amber,
    amberLight: "rgba(255,159,10,0.15)",
    purple: palette.purple,
    purpleLight: "rgba(175,82,222,0.15)",
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.mint,
    danger: palette.coral,
    warning: palette.amber,
    success: palette.mint,
  },
};
